#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/update-checker.yml
# Description: Source code update checker (multi-repo)
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Update Checker

on:
  workflow_dispatch:
#  schedule:
#    - cron: 0 */18 * * *

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: padavanonly-mt798x-6.6
            repo_url: https://github.com/padavanonly/immortalwrt-mt798x-6.6
            repo_branch: openwrt-24.10-6.6
          - project: hanwckf-mt798x
            repo_url: https://github.com/hanwckf/immortalwrt-mt798x
            repo_branch: openwrt-21.02
          - project: immortalwrt
            repo_url: https://github.com/immortalwrt/immortalwrt
            repo_branch: master

    steps:
    - name: Get Commit Hash
      id: getHash
      run: |
        git clone --depth 1 ${{ matrix.repo_url }} -b ${{ matrix.repo_branch }} repo
        cd repo
        echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v3
      with:
        path: .commitHash
        key: commitHash_${{ matrix.project }}_${{ steps.getHash.outputs.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash

    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ github.token }}
        event-type: Source Code Update

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 2
